version: '3.1'

services:
  db:
    container_name: tms_db
    image: mysql:8.0.26
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: some-password
    networks:
      - tms_dev_db

  admin-tool:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.1
    ports:
      - '4242:80'
    depends_on:
      - db
    environment:
      #      PMA_HOST: tms_db
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 10000K
    networks:
      - tms_dev_db

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - '2000:3000'
    networks:
      - tms_dev_db

networks:
  tms_dev_db:
