version: '3'
services:
  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    depends_on:
      - tms-server
    ports:
      - '80:80'
      - '443:443'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - proxy_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/certs:/etc/nginx/certs

networks:
  proxy_network:
