services:
  mysql:
    container_name: tms_db
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: some-password
    networks:
      - tms_dev_db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - '4242:80'
    depends_on:
      - mysql
    environment:
      PMA_HOST: tms_db
    networks:
      - tms_dev_db

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - '2000:3000'
    networks:
      - tms_dev_db

networks:
  tms_dev_db:
