version: '3.8'
services:
  sql-db:
    image: mysql:latest
    container_name: tms_sql_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test-sql-password
    networks:
      - tms_db

  tms-server:
    image: dudrie/tms-test:0.0.0-pre
    container_name: tms-test
    depends_on:
      - sql-db
    ports:
      - '8080:8080'
    networks:
      - tms_db
    environment:
      TMS_SQL_DB_USER: root
      TMS_SQL_DB_PW: test-sql-password
      TMS_SECRET: keyboard cat
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./config:/tms/server/config

gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - '2000:3000'
    networks:
      - tms_db

volumes:
  db_data:

networks:
  tms_db:
